name       : pidgin
version    : 2.14.1
release    : 26
source     :
    - https://netcologne.dl.sourceforge.net/project/pidgin/Pidgin/2.14.1/pidgin-2.14.1.tar.bz2 : f132e18d551117d9e46acce29ba4f40892a86746c366999166a3862b51060780
homepage   : https://www.pidgin.im
license    : GPL-2.0-or-later
component  :
    - network.im
    - devel : programming.devel
    - ^finch : network.im
    - ^finch-devel : programming.devel
    - ^libpurple : programming.library
    - ^libpurple-devel : programming.devel
summary    :
    - Graphical multi-protocol IM client
    - devel : Development files for Pidgin
    - ^finch : Finch is the command line client part of Pidgin
    - ^finch-devel : Development files for finch
    - ^libpurple : libpurple is intended to be the core of an IM program.
    - ^libpurple-devel : Development files for libpurple
description:
    - Pidgin is a graphical multi-protocol IM client that runs on Microsoft Windows and Unixes. It is written in C and uses Glib and GTK+. It also provides libpurple, a library used for developing IM programs.
    - devel : Development files for Pidgin
    - ^finch : Finch is the command line client part of Pidgin
    - ^finch-devel : Development files for finch
    - ^libpurple : libpurple is intended to be the core of an IM program. Programs are written using this library as the backend for chat programs. Pidgin is the GTK+ frontend, and Finch is the ncurses/command line frontend.
    - ^libpurple-devel : Development files for libpurple
patterns   :
    - ^finch :
        - /usr/bin/finch
        - /usr/lib64/finch
        - /usr/lib64/libgnt*.so.*
        - /usr/lib64/gnt
        - /usr/share/man/man1/finch*
    - ^finch-devel :
        - /usr/include/finch
        - /usr/include/gnt
        - /usr/lib64/libgnt*.so
        - /usr/lib64/pkgconfig/gnt*
        - /usr/lib64/pkgconfig/finch*
    - ^libpurple :
        - /usr/bin/purple*
        - /usr/lib64/libpurple*.so.*
        - /usr/lib64/purple-2
        - /usr/share/locale
        - /usr/share/purple
        - /usr/share/sounds
    - ^libpurple-devel :
        - /usr/include/libpurple
        - /usr/lib64/libpurple*.so
        - /usr/lib64/pkgconfig/purple*
        - /usr/share/aclocal
        - /usr/share/man/man3
    - devel :
        - /usr/include/pidgin
        - /usr/lib64/pkgconfig/pidgin.pc
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(farstream-0.2)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(libnm)
    - pkgconfig(nss)
    - pkgconfig(sm)
    - pkgconfig(xscrnsaver)
    - libgnt-devel
setup      : |
    %reconfigure --disable-idn \
               --disable-meanwhile \
               --disable-schemas-install \
               --disable-tcl \
               --enable-consoleui
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/lib
